---
title: "HW8"
author: "Chrinovic Mukulu"
date: "2025-11-03"
output: pdf_document
---

```{r}
#Question 1
library(readr)
ss06hid <- read_csv("ss06hid.csv")
View(ss06hid)
fileUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv"
download.file(fileUrl, destfile = "ss06hid.csv",)
Housing<- read.csv("ss06hid.csv")

agricultureLogical<- Housing$ACR == 3 & Housing$AGS == 6


which(agricultureLogical)[1:3]
```


```{r}
#Question 2

library(jpeg)
url<- "https://drive.google.com/uc?export=download&id=10KOr-BZuoL0bVcce8tlM7_GvQyECpjPp"
download.file(url, destfile = "hw8pic.jpg", mode = "wb")
img<- readJPEG("hw8pic.jpg", native = TRUE)

quantile(img, probs = c(0.3,0.8))
```


```{r}
#Question 3

gdp <- read.csv("getdata_data_GDP.csv", skip = 4, stringsAsFactors = FALSE)
edu <- read.csv("getdata_data_EDSTATS_Country.csv", stringsAsFactors = FALSE)

gdp <- gdp[!is.na(gdp$X), ] 
names(gdp)[1:5] <- c("CountryCode", "Rank", "Economy", "GDP", "Extra")
merged <- merge(gdp[, c("CountryCode", "Rank", "Economy", "GDP")],
                edu,
                by = "CountryCode")

merged$Rank <- as.numeric(merged$Rank)

tapply(merged$Rank, merged$Income.Group, mean, na.rm = TRUE)[
  c("High income: OECD", "High income: nonOECD")
]


merged$gdpGroup <- cut(merged$Rank,
                       breaks = quantile(merged$Rank, probs = seq(0,1,0.2), na.rm = TRUE),
                       include.lowest = TRUE)
table(merged$gdpGroup, merged$Income.Group)

topGroup <- merged$gdpGroup == levels(merged$gdpGroup)[1]

sum(topGroup & merged$Income.Group == "Lower middle income")


```